[tool.poetry]
name = "starlette-authlib"
version = "0.1.12"
description = "A drop-in replacement for Starlette session middleware, using authlib's jwt"
authors = ["Alessandro Ogier <alessandro.ogier@gmail.com>"]
readme = "README.md"
repository = "https://github.com/aogier/starlette-authlib"

[tool.poetry.dependencies]
python = "^3.7"
authlib = "<1.2"
uvicorn = "<0.19"
starlette = "<0.22"

[tool.poetry.dev-dependencies]
pytest = "^7"
mypy = "^0.981"
requests = "^2.28.1"
black = "^22"
autoflake = "^1.6"
pytest-cov = "^4"
changelog-cli = "^0.7.1"
codecov = "^2.1.12"
httpx = "^0.23.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
